#!/bin/bash

canister=${2:progenitus}

function deploy {
    if [ "$1" == "ic" ]; then
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy --no-wallet --network=ic $canister --argument "(\"ryjl3-tyaaa-aaaaa-aaaba-cai\")"
        progenitusId=$(dfx canister --network=ic id $canister)
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy --no-wallet --network=ic mock_nft --argument "(\"$progenitusId\")"
    else
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy mock_ledger
        ledgerId=$(dfx canister id mock_ledger)
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy $canister --argument "(\"$ledgerId\")"
        progenitusId=$(dfx canister id $canister)
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy mock_nft --argument "(\"$progenitusId\")"
    fi
}

deploy "$@"
