#!/bin/bash

function deploy {
    if [ "$1" == "ic" ]; then
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy --no-wallet --network=ic progenitus --argument "(\"ryjl3-tyaaa-aaaaa-aaaba-cai\")"
        progenitusId=$(dfx canister id progenitus)
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy --no-wallet --network=ic mock_nft --argument "(\"$progenitusId\")"
    else
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy mock_ledger
        ledgerId=$(dfx canister id mock_ledger)
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy progenitus --argument "(\"$ledgerId\")"
        progenitusId=$(dfx canister id progenitus)
        DFX_MOC_PATH="$(vessel bin)/moc" dfx deploy mock_nft --argument "(\"$progenitusId\")"
    fi
}

deploy "$@"
