#!/bin/bash

$(vessel bin)/moc $(vessel sources 2> /dev/null) --check "main.mo"
for i in $(find src mock -name '*.mo'); do
    echo "$i"
    $(vessel bin)/moc $(vessel sources 2> /dev/null) --check $i
done
