name: Test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.9.3
          vessel-version: 0.6.3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: ./.scripts/moc-test
      - run: |
          cp .env.example .env
          npm i
          npm run make-admin
          npm run test:dfx
